"""create initial tables

Revision ID: 529866b46a21
Revises: 
Create Date: 2026-05-11 17:11:40.992282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '529866b46a21'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cpu_brands',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('criteria',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('criteria_code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('attribute_type', sa.String(length=20), nullable=False),
    sa.Column('default_weight', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('criteria_code')
    )
    op.create_table('displays',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('resolution', sa.String(length=50), nullable=False),
    sa.Column('refresh_rate', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('laptop_brands',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('laptop_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('operating_systems',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('storages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('storage_type', sa.String(length=50), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vga_brands',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('processors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('cpu_ranking_score', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['cpu_brands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vgas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('gpu_benchmark_score', sa.Integer(), nullable=False),
    sa.Column('memory_capacity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['vga_brands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('laptops',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('os_id', sa.Integer(), nullable=False),
    sa.Column('processor_id', sa.Integer(), nullable=False),
    sa.Column('vga_id', sa.Integer(), nullable=False),
    sa.Column('display_id', sa.Integer(), nullable=False),
    sa.Column('ram_capacity', sa.Integer(), nullable=False),
    sa.Column('ram_type', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('battery_backup', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['laptop_brands.id'], ),
    sa.ForeignKeyConstraint(['display_id'], ['displays.id'], ),
    sa.ForeignKeyConstraint(['os_id'], ['operating_systems.id'], ),
    sa.ForeignKeyConstraint(['processor_id'], ['processors.id'], ),
    sa.ForeignKeyConstraint(['type_id'], ['laptop_types.id'], ),
    sa.ForeignKeyConstraint(['vga_id'], ['vgas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('laptop_storages',
    sa.Column('laptop_id', sa.Integer(), nullable=False),
    sa.Column('storage_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['laptop_id'], ['laptops.id'], ),
    sa.ForeignKeyConstraint(['storage_id'], ['storages.id'], ),
    sa.PrimaryKeyConstraint('laptop_id', 'storage_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('laptop_storages')
    op.drop_table('laptops')
    op.drop_table('vgas')
    op.drop_table('processors')
    op.drop_table('vga_brands')
    op.drop_table('storages')
    op.drop_table('operating_systems')
    op.drop_table('laptop_types')
    op.drop_table('laptop_brands')
    op.drop_table('displays')
    op.drop_table('criteria')
    op.drop_table('cpu_brands')
    # ### end Alembic commands ###
